# Update dependencies

version: 2
updates:
  # Update the git submodules
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'automerge'
